### ISSUE TITLE
Update to Angular 17

### ISSUE THREAD

**Issue by zjkipping** [OasisDigital/ng-doc-portal#10]
Need to update angular version to v17, should also update Nx version as well. Shouldn't be a terrible update, but we can swap our internal application to use esbuild instead of webpack which will be a nice performance boost :)

**Comment by zjkipping** [comment]
Resolved in release [`v1.8.0`](https://github.com/OasisDigital/ng-doc-portal/releases/tag/v1.8.0)

**Comment by zjkipping** [comment]
Build consistently fails since the package.json and package-lock.json can't seem to reconcile themselves. Might have to rebuild the entire repo to make it work, don't have time for it today...

**Comment by wnodom** [comment]
I recently ran into what sure sounds like a similar issue. The longer notes are below, but here's the short version of how I eventually coerced `npm` into generating a `package-lock.json` that wouldn't freak out `npm ci`:

```
$ rm package-lock.json

$ rm -rf node_modules

$ npm cache clean -f

$ npm install

$ npm install  # again!
```

Honestly, removing `node_modules` and nuking the cache might not be necessary, but that's what I did right before I finally got it working, and by that time I was too desperate and superstitious to stop.

Anyway, here's a little more info, in case it provides any clues to the problem you're having:

```
$ node -v
v20.9.0

$ npm -v
9.8.1

$ rm -rf node_modules

$ npm cache clean -f

$ rm package-lock.json

$ npm install
```

At this point, the installed modules and `package-lock.json` are incorrect. Here’s an example error:

```
$ npm ls js-yaml 
npm ERR! code ELSPROBLEMS 
npm ERR! invalid: js-yaml@3.14.1 /workspace/node_modules/js-yaml 
@sicura/source@0.0.0 /workspace 
+-- @angular-devkit/build-angular@17.2.2 
| +-- babel-plugin-istanbul@6.1.1 
| | `-- @istanbuljs/load-nyc-config@1.1.0 
| |   `-- js-yaml@3.14.1 deduped invalid: "4.1.0" from node_modules/@nx/eslint 
| `-- postcss-loader@8.1.0 
|   `-- cosmiconfig@9.0.0 
|     `-- js-yaml@4.1.0 
+-- @nx/eslint@18.1.0-beta.2 
| `-- js-yaml@3.14.1 invalid: "4.1.0" from node_modules/@nx/eslint 
+-- eslint@8.48.0 
| +-- @eslint/eslintrc@2.1.4 
| | `-- js-yaml@4.1.0 
| `-- js-yaml@4.1.0 
`-- nx@18.1.0-beta.2 
  +-- @yarnpkg/parsers@3.0.0-rc.46 
  | `-- js-yaml@3.14.1 deduped invalid: "4.1.0" from node_modules/@nx/eslint 
  `-- js-yaml@4.1.0 

```

Attempting a clean install breaks:

```
$ rm -rf node_modules

$ npm ci

...lots of output deleted...

npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Invalid: lock file's js-yaml@3.14.1 does not satisfy js-yaml@4.1.0
npm ERR! Missing: js-yaml@3.14.1 from lock file
npm ERR! Missing: js-yaml@3.14.1 from lock file
npm ERR! Invalid: lock file's argparse@1.0.10 does not satisfy argparse@2.0.1
npm ERR! Missing: argparse@1.0.10 from lock file
npm ERR! Missing: argparse@1.0.10 from lock file

...lots of output deleted...

```

Running `npm install` again seems to fix the install and produce a correct `package-lock.json`, with no need to remove `node_modules` or clean the cache.

Running `npm install` a third time doesn’t change `package-lock.json`, so... I guess twice is enough?

**Comment by zjkipping** [comment]
@wnodom Weird I went through wiping node_modules & cache + lock multiple times as well. Though I guess I didn't repeat it enough...

**Comment by zjkipping** [comment]
Closed with merge of https://github.com/OasisDigital/ng-doc-portal/pull/11
