### ISSUE TITLE
Customize Default Landing Page

### ISSUE THREAD

**Issue by Bill77** [OasisDigital/ng-doc-portal#9]
Hi @zjkipping :)

It would be great to be able to customize the default landing page instead of the default route to `<ngdp-no-selection-page>` component. Also with a custom landing page, be great if clicking on the title bar takes us back there. 

> Trying to make it more user friendly, and I wanted a place inform people how to report defects. :)

**Comment by zjkipping** [comment]
Hello @Bill77, I'll get this triaged and worked on this week :) If not I'll comment back here on when I can get to it.

**Comment by zjkipping** [comment]
@Bill77 Will start this today

**Comment by Bill77** [comment]
Thanks @zjkipping, will try it out this week, and report back any issues 😉
